# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgbrowser < Formula
  desc "k9s-style TUI for browsing PostgreSQL clusters"
  homepage "https://github.com/zagware/pgbrowser-dist"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zagware/pgbrowser-dist/releases/download/v0.1.0/pgbrowser_darwin_amd64.tar.gz"
      sha256 "6d7c4bfa1119b3b8529caca209a234b3391187cdcb5c043e3d47ffc67af12e18"

      define_method(:install) do
        bin.install "pgbrowser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zagware/pgbrowser-dist/releases/download/v0.1.0/pgbrowser_darwin_arm64.tar.gz"
      sha256 "ee972594c483c25e3c91144d910b2eceb8cedef2bb988b28ecab91daaa16eb6e"

      define_method(:install) do
        bin.install "pgbrowser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zagware/pgbrowser-dist/releases/download/v0.1.0/pgbrowser_linux_amd64.tar.gz"
      sha256 "0679aaf72bd4bcb6206862514005978243b89cafa408637792149682cdfe749b"
      define_method(:install) do
        bin.install "pgbrowser"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zagware/pgbrowser-dist/releases/download/v0.1.0/pgbrowser_linux_arm64.tar.gz"
      sha256 "8ee51733a8f575eb64dc712e92a0dcd70e51f71d563d0338ae166b053e5dda8b"
      define_method(:install) do
        bin.install "pgbrowser"
      end
    end
  end

  test do
    system "#{bin}/pgbrowser", "version"
  end
end
