# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgbrowser < Formula
  desc "k9s-style TUI for browsing PostgreSQL clusters"
  homepage "https://github.com/zagware/pgbrowser-dist"
  version "0.2.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zagware/pgbrowser-dist/releases/download/v0.2.1/pgbrowser_darwin_amd64.tar.gz"
      sha256 "4b580a236109fde8c59130aabada794ef4f7f7bd9c0ee43a7fca07a657fe247b"

      define_method(:install) do
        bin.install "pgbrowser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zagware/pgbrowser-dist/releases/download/v0.2.1/pgbrowser_darwin_arm64.tar.gz"
      sha256 "faf3a9ad228687e2dc85d441df4ca339d368deeaccffd7f922cac23a61ed7d1d"

      define_method(:install) do
        bin.install "pgbrowser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zagware/pgbrowser-dist/releases/download/v0.2.1/pgbrowser_linux_amd64.tar.gz"
      sha256 "bdaa60c9ca09675758f10e35d5d3e1155fcb3f46ca6d29cc7895b6472ebfe1ef"
      define_method(:install) do
        bin.install "pgbrowser"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zagware/pgbrowser-dist/releases/download/v0.2.1/pgbrowser_linux_arm64.tar.gz"
      sha256 "f8f0a0091b72b699ecce3e21a225fdfefa841f91098a442733ebca68c7ec2538"
      define_method(:install) do
        bin.install "pgbrowser"
      end
    end
  end

  test do
    system "#{bin}/pgbrowser", "version"
  end
end
